var write = 'shape\n'

log('\n', undefined)
// var add = ui.add()
var ui_show = ui.show()
var ui_setTitle = ui.setTitle('Test')
var ui_addStretch = ui.addStretch()
var ui_addSpacing = ui.addSpacing()
var ui_setSpaceBetween = ui.setSpaceBetween()
var ui_setMargins = ui.setMargins()
var ui_scriptLocation = ui.scriptLocation()
var ui_resize = ui.resize(400, 800)
var ui_addCallbackObject = ui.addCallbackObject()

log('\n', undefined)
var button = new ui.Button('button')
var button_setText = button.setText()
var button_setSize = button.setSize()
var button_setFixedHeight = button.setFixedHeight()
var button_setFixedWidth = button.setFixedWidth()
var button_setImage = button.setImage()
var button_setDrawStroke = button.setDrawStroke()
var button_onClick = button.onClick()
var button_setEnabled = button.setEnabled()
var button_isEnabled = button.isEnabled()
var button_setBackgroundColor = button.setBackgroundColor()
var button_addButton = ui.add(button)

log('\n', undefined)
var checkbox = new ui.Checkbox(true)
var checkbox_getValue = checkbox.getValue()
var checkbox_setValue = checkbox.setValue()
var checkbox_onValueChanged = checkbox.onValueChanged()
var checkbox_setEnabled = checkbox.setEnabled()
var checkbox_isEnabled = checkbox.isEnabled()
var checkbox_setSize = checkbox.setSize()
var checkbox_setFixedHeight = checkbox.setFixedHeight()
var checkbox_setFixedWidth = checkbox.setFixedWidth()
var checkbox_setToolTip = checkbox.setToolTip()
var checkbox_addCheckbox = ui.add(checkbox)

log('\n', undefined)
var colorchip = new ui.ColorChip()
var colorchip_getColor = colorchip.getColor()
var colorchip_getColorWithAlpha = colorchip.getColorWithAlpha()
var colorchip_setColor = colorchip.setColor()
var colorchip_onValueChanged = colorchip.onValueChanged()
var colorchip_setEnabled = colorchip.setEnabled()
var colorchip_isEnabled = colorchip.isEnabled()
var colorchip_setSize = colorchip.setSize()
var colorchip_setFixedHeight = colorchip.setFixedHeight()
var colorchip_setFixedWidth = colorchip.setFixedWidth()
var colorchip_setToolTip = colorchip.setToolTip()
var colorchip_addColorchip = ui.add(colorchip)

log('\n', undefined)
var colorpalette = new ui.ColorPalette()
var colorpalette_getColors = colorpalette.getColors()
var colorpalette_setColors = colorpalette.setColors()
var colorpalette_setEnabled = colorpalette.setEnabled()
var colorpalette_isEnabled = colorpalette.isEnabled()
var colorpalette_setSize = colorpalette.setSize()
var colorpalette_setFixedHeight = colorpalette.setFixedHeight()
var colorpalette_setFixedWidth = colorpalette.setFixedWidth()
var colorpalette_setToolTip = colorpalette.setToolTip()
var colorpalette_addColorpalette = ui.add(colorpalette)

log('\n', undefined)
var colorpicker = new ui.ColorPicker()
var colorpicker_getColor = colorpicker.getColor()
var colorpicker_addColorpicker = ui.add(colorpicker)

log('\n', undefined)
var colorwheel = new ui.ColorWheel()
var colorwheel_getColor = colorwheel.getColor()
var colorwheel_setColor = colorwheel.setColor()
var colorwheel_onColorChanged = colorwheel.onColorChanged()
var colorwheel_addColorwheel = ui.add(colorwheel)

log('\n', undefined)
var dropdown = new ui.DropDown()
var dropdown_getValue = dropdown.getValue()
var dropdown_getText = dropdown.getText()
var dropdown_addEntry = dropdown.addEntry()
var dropdown_setValue = dropdown.setValue()
var dropdown_setText = dropdown.setText()
var dropdown_onValueChanged = dropdown.onValueChanged()
var dropdown_populateFontFamilies = dropdown.populateFontFamilies()
var dropdown_populateStylesForFamily = dropdown.populateStylesForFamily()
var dropdown_setEnabled = dropdown.setEnabled()
var dropdown_isEnabled = dropdown.isEnabled()
var dropdown_setSize = dropdown.setSize()
var dropdown_setFixedHeight = dropdown.setFixedHeight()
var dropdown_setFixedWidth = dropdown.setFixedWidth()
var dropdown_setToolTip = dropdown.setToolTip()
var dropdown_addDropdown = ui.add(dropdown)

log('\n', undefined)
var filepath = new ui.FilePath()
var filepath_getFilePath = filepath.getFilePath()
var filepath_setFilePath = filepath.setFilePath()
var filepath_setMode = filepath.setMode()
var filepath_setFilter = filepath.setFilter()
var filepath_setEnabled = filepath.setEnabled()
var filepath_isEnabled = filepath.isEnabled()
var filepath_setToolTip = filepath.setToolTip()
var filepath_addFilepath = ui.add(filepath)

log('\n', undefined)
var hlayout = new ui.HLayout()
var hlayout_add = hlayout.add()
var hlayout_addStretch = hlayout.addStretch()
var hlayout_addSpacing = hlayout.addSpacing()
var hlayout_setSpaceBetween = hlayout.setSpaceBetween()
var hlayout_setMargins = hlayout.setMargins()
var hlayout_addHlayout = ui.add(hlayout)

log('\n', undefined)
var image = new ui.Image('/Users/Remco/Desktop/bun.jpg')
var image_setSize = image.setSize(100, 100)
var image_setFixedHeight = image.setFixedHeight(100)
var image_setFixedWidth = image.setFixedWidth(100)
var image_setImage = image.setImage()
var image_setToolTip = image.setToolTip('tooltip')
var image_addImage = ui.add(image)

log('\n', undefined)
var imagebutton = new ui.ImageButton('/Users/Remco/Desktop/bun.jpg')
var imagebutton_setSize = imagebutton.setSize(64, 64)
var imagebutton_setFixedHeight = imagebutton.setFixedHeight(64)
var imagebutton_setFixedWidth = imagebutton.setFixedWidth(64)
var imagebutton_setImage = imagebutton.setImage()
var imagebutton_setDrawStroke = imagebutton.setDrawStroke(true)
var imagebutton_setStateButton = imagebutton.setStateButton(true)
var imagebutton_setState = imagebutton.setState(false)
var imagebutton_getState = imagebutton.getState()
var imagebutton_onClick = imagebutton.onClick()
var imagebutton_setEnabled = imagebutton.setEnabled(false)
var imagebutton_isEnabled = imagebutton.isEnabled()
var imagebutton_setToolTip = imagebutton.setToolTip('tooltip')
var imagebutton_addImagebutton = ui.add(imagebutton)

log('\n', undefined)
var label = new ui.Label()
var label_setText = label.setText()
var label_setTextColor = label.setTextColor()
var label_setAlignment = label.setAlignment()
var label_setEnabled = label.setEnabled()
var label_isEnabled = label.isEnabled()
var label_setSize = label.setSize()
var label_setFixedHeight = label.setFixedHeight()
var label_setFixedWidth = label.setFixedWidth()
var label_setToolTip = label.setToolTip()
var label_setBackgroundColor = label.setBackgroundColor()
var label_setFontSize = label.setFontSize()
var label_addLabel = ui.add(label)

log('\n', undefined)
var lineedit = new ui.LineEdit()
var lineedit_getText = lineedit.getText()
var lineedit_setPlaceholder = lineedit.setPlaceholder()
var lineedit_setReadOnly = lineedit.setReadOnly()
var lineedit_setEnabled = lineedit.setEnabled()
var lineedit_isEnabled = lineedit.isEnabled()
var lineedit_setSize = lineedit.setSize()
var lineedit_setFixedHeight = lineedit.setFixedHeight()
var lineedit_setFixedWidth = lineedit.setFixedWidth()
var lineedit_setToolTip = lineedit.setToolTip()
var lineedit_addLineedit = ui.add(lineedit)

log('\n', undefined)
var multilineedit = new ui.MultiLineEdit()
var multilineedit_getText = multilineedit.getText()
var multilineedit_setPlaceholder = multilineedit.setPlaceholder()
var multilineedit_setBackgroundColor = multilineedit.setBackgroundColor()
var multilineedit_setReadOnly = multilineedit.setReadOnly()
var multilineedit_setEnabled = multilineedit.setEnabled()
var multilineedit_isEnabled = multilineedit.isEnabled()
var multilineedit_setSize = multilineedit.setSize()
var multilineedit_setFixedHeight = multilineedit.setFixedHeight()
var multilineedit_setFixedWidth = multilineedit.setFixedWidth()
var multilineedit_setToolTip = multilineedit.setToolTip()
var multilineedit_addMultiLineedit = ui.add(multilineedit)

log('\n', undefined)
var numericfield = new ui.NumericField()
var numericfield_getValue = numericfield.getValue()
var numericfield_setValue = numericfield.setValue()
var numericfield_setMin = numericfield.setMin()
var numericfield_setMax = numericfield.setMax()
var numericfield_setType = numericfield.setType()
var numericfield_setEnabled = numericfield.setEnabled()
var numericfield_isEnabled = numericfield.isEnabled()
var numericfield_setSize = numericfield.setSize()
var numericfield_setToolTip = numericfield.setToolTip()
var numericfield_onValueChanged = numericfield.onValueChanged()
var numericfield_addNumericfield = ui.add(numericfield)

log('\n', undefined)
var pageview = new ui.PageView()
var pageview_add = pageview.add()
var pageview_setPage = pageview.setPage()
var pageview_currentPage = pageview.currentPage()
var pageview_pageCount = pageview.pageCount()
var pageview_addPageview = ui.add(pageview)

log('\n', undefined)
var slider = new ui.Slider()
var slider_getValue = slider.getValue()
var slider_setValue = slider.setValue()
var slider_setRange = slider.setRange()
var slider_onValueChanged = slider.onValueChanged()
var slider_addSlider = ui.add(slider)

log('\n', undefined)
var progressbar = new ui.ProgressBar()
var progressbar_getValue = progressbar.getValue()
var progressbar_setValue = progressbar.setValue()
var progressbar_setMaximum = progressbar.setMaximum()
var progressbar_addProgressbar = ui.add(progressbar)

log('\n', undefined)
var tabview = new ui.TabView()
var tabview_add = tabview.add()
var tabview_setTab = tabview.setTab()
var tabview_currentTab = tabview.currentTab()
var tabview_tabCount = tabview.tabCount()
var tabview_onValueChanged = tabview.onValueChanged()
var tabview_addTabview = ui.add(tabview)

log('\n', undefined)
var vlayout = new ui.VLayout()
var vlayout_add = vlayout.add()
var vlayout_addStretch = vlayout.addStretch()
var vlayout_addSpacing = vlayout.addSpacing()
var vlayout_setSpaceBetween = vlayout.setSpaceBetween()
var vlayout_setMargins = vlayout.setMargins()
var vlayout_addSeparator = vlayout.addSeparator()
var vlayout_addVlayout = ui.add(vlayout)

log('\n', undefined)
var timer = new ui.Timer()
var timer_start = timer.start()
var timer_stop = timer.stop()
var timer_isActive = timer.isActive()
var timer_setInterval = timer.setInterval()
var timer_setRepeating = timer.setRepeating()
var timer_onTimeout = timer.onTimeout()
var timer_addTimer = ui.add(timer)

/**
 * @param {any} item
 */
function getTypeof(item) {
	return Array.isArray(item) ? 'array' : typeof item
}

/**
 * @param {any} item
 */
function getValue(item) {
	return getTypeof(item) === 'object' ? JSON.stringify(item) : item
}

/**
 * @param {string} itemName
 * @param {any} item
 */
function log(itemName, item) {
	var value = `${itemName}, ${getTypeof(item)}, ${getValue(item)}`
	console.log(value)
	write += `${value}\n`
}
api.writeToFile('/Users/Remco/Desktop/test.csv', write)
